### PR TITLE
Update for 0.12

### PR DESCRIPTION
**Pull request by RAbraham**
Updating the project for 0.12 as per the [discussion](https://github.com/lpil/purescript-aws-lambda-express/issues/2). This mostly includes moving to `purescript-effect` and `purescript-exceptions`.

### CODE REVIEW

**Comment by lpil** [comment]
Great, thank you.

**Review by lpil — APPROVED** [review]

**Comment by lpil** [comment]
Hi @RAbraham 

After merging this `pulp build` no longer succeeds. Do you also have this problem?

I'm afraid I'm no longer a purescript user so it's not obvious to me what the problem is.

Once this is fixed I can look into releasing a new version.

**Comment by RAbraham** [comment]
Hi @lpil 
Yes, the failure is, I think, because of `purescript-express`. I have raised an issue [here](https://github.com/nkly/purescript-express/issues/91). 

If you run ` bower install purescript-test-unit` (which is a dependency of `purescript-express`), it should work. So, I think, it's not something we need to change in `purescript-aws-lambda-express` as we don't use `purescript-test-unit`.

**Comment by lpil** [comment]
Thank you. I've released a new version

**Pull request merged**
